# .github/workflows/build-and-deploy.yaml
name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

env:
  env_name: MyProject
      
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      env_name: ${{ env.env_name }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
