name: Build Service

on:
  push:
    branches: 
        - master1
  workflow_dispatch:
  workflow_call:
    inputs:
        env_name:
          required: true
          type: string

jobs:
  build_service:
    runs-on: ubuntu-latest
    name: "${{ inputs.env_name }} Build Service "
    steps:
    - name: service 1
      run: |-
        echo "Building the project: ${{ inputs.env_name }}"
