name: Build Service

on:
  push:
    branches: 
        - master1
  workflow_dispatch:
  workflow_call:
    inputs:
        PROJECT_NAME:
          required: true
          type: string

jobs:
  build_service:
    runs-on: ubuntu-latest
    name: "Build Service "
    steps:
    - name: service 1
      run: |-
        echo "Building the project: ${{ inputs.PROJECT_NAME }}"
