# .github/workflows/build-and-deploy.yaml
name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:


      
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      PROJECT_NAME: Dev

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
