name: Custom Action Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      action_path:
        description: "Path to the custom action"
        required: true
        default: "./.github/custom-action/add-steps"

jobs:
  run-custom-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Files
      run: |-
        echo ls -R

    - name: Run Custom Action
      uses: ./.github/custom-action/add-steps
      with:
        message: "Hello from the custom action!"
