name: Deploy Service

on:
  push:
    branches: 
        - master1
  workflow_dispatch:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
    


jobs:
  deploy_service:
    runs-on: ubuntu-latest
    name: Deploy Service 
    steps:
    - name: service 1
      run: echo "version is ${{ inputs.VERSION }}"
