name: Dev Build and Deployment

on:
  push:
    branches: 
        - feature/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build Service
    steps:
    - name: service 1
      run: echo "${{ github.workflow }}-${{ github.ref }}"
  Deploy_Dev:
    runs-on: ubuntu-latest
    name: Dev Deploy
    needs: Build
    steps:
    - name: service 1
      run: echo "Deploy on Dev"
  Deploy_UAT:
    runs-on: ubuntu-latest
    name: Uat Deploy
    needs: Deploy_Dev
    environment:
        name: UAT
    steps:
    - name: service 1
      run: echo "Deploy on UAT"
  