name: Build Artifact

on:
  push:
    branches:
      - main
      - master
      - release/*
      - development
  workflow_dispatch:

jobs:
  Build_Service_One:
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: "echo"

  Build_Service_Two:
    runs-on: ubuntu-latest
    steps:
    - name: Action 1
      run: echo "This is Action 1"

  Build_Service_Three:
    runs-on: ubuntu-latest
    steps:
    - name: Action 2
      run: echo "This is Action 2"
  
  Deploy_Service_One-UAT-Azure:
    needs: [ Build_Service_One ]
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: "echo"
  Deploy_Service_Two-UAT-Azure:
    needs: [ Build_Service_Two ]
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: "echo"
        
  Deploy_Service_Three-UAT-Azure:
    needs: [ Build_Service_Three ]
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: "echo"

  Deploy_Service_One-UAT-GCP:
      needs: [ Build_Service_One ]
      runs-on: ubuntu-latest
      steps:
        - name: using acheck out actions
          uses: actions/checkout@v2
        - name: Run online script
          run: "echo"
  Deploy_Service_Two-UAT-GCP:
    needs: [ Build_Service_Two ]
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: "echo"
          
  Deploy_Service_Three-UAT-Gcp:
    needs: [ Build_Service_Three ]
    runs-on: ubuntu-latest
    steps:
      - name: using acheck out actions
        uses: actions/checkout@v2
      - name: Run online script
        run: |-
        
          echo "hello"
          SUMMARY="# Docker image created 🚀 /n __Docker Image Spec__: _docker path_ /n 
          `Docker Image Spec: _docker path`
          > [!NOTE]> Useful information that users should know, even when skimming content."
    
