name: End to End Test and Deployment

on:
  push:
    branches: 
        - master
  workflow_dispatch:

jobs:
  build_service_one:
    runs-on: ubuntu-latest
    name: Build Service One
    steps:
    - name: service 1
      run: echo "This is service 1"

  deploy_service_one_e2e:
    runs-on: ubuntu-latest
    needs: build_service_one
    name: Deploy Service One
    steps:
    - name: service deploy 1
      run: echo "This is service deploy 1"

  build_service_two:
    runs-on: ubuntu-latest
    name: Build Service Two
    steps:
    - name: service 2
      run: echo "This is service 2"

  deploy_service_two_e2e:
    runs-on: ubuntu-latest
    name: Deploy Service Two
    needs: build_service_two
    steps:
    - name: service 2
      run: echo "This is service 2"

  build_deploy_ui_e2e:
    runs-on: ubuntu-latest
    name: Build and Deploy UI to E2E
    steps:
    - name: service 2
      run: echo "This is service 2"

  e2e_tests:
    runs-on: ubuntu-latest
    name: Run full end to end regression tests
    needs:
      - deploy_service_one_e2e
      - deploy_service_two_e2e
      - build_deploy_ui_e2e
    steps:
    - name: service 1
      run: echo "This is service 1"

  deploy_service_one_prod:
    runs-on: ubuntu-latest
    needs: 
      - build_service_one 
      - e2e_tests
    name: Deploy Service One to Production
    steps:
    - name: service 1
      run: echo "This is service 1"

  deploy_service_two_prod:
    runs-on: ubuntu-latest
    name: Deploy Service Two to Production
    needs:
      - build_service_two
      - e2e_tests
    steps:
    - name: service 1
      run: echo "This is service 1"
  
  build_deploy_ui_prod:
    runs-on: ubuntu-latest
    name: Build and Deploy UI to Prod
    needs: e2e_tests
    steps:
    - name: service 1
      run: echo "This is service 1"
  