name: Git Variables Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  one: 1
  two: zwei
  three: tres
  projectName: dev

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ env.one }}"
        echo "${{ env.two }}"
        echo "${{ env.three }}"
        
  build:
    uses: ./.github/workflows/build.yaml
    with:
      PROJECT_NAME: ${{ projectName }}
