# .github/workflows/deploy-service.yml
name: Test YQ Service

on:
  push:
  workflow_dispatch: 

jobs:
  yq_test:
    outputs: 
        output_test: ${{ steps.get-config.outputs.output_test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check YQ
        id: get-config
        run: |
         ls -R
         JSON_OUTPUT=$(yq '.batches | to_entries | map([.value[]] | join(","))' .github/input.yaml)
         JSON_OUTPUT1=$(yq '.batches | .[] | join(", ")' .github/input.yaml)
         JSON_OUTPUT2=$(yq '.batches | to_entries | map("\"" + (.value | join(", ")) + "\"") | join(", ")' .github/input.yaml | paste -sd "," -)

         output_test=$(yq -o=json '.batches | to_entries | map(.value | join(","))' .github/input.yaml)
         json_single_line=$(yq -o=json '.batches | to_entries | map(.value | join(","))' .github/input.yaml | jq -s -c)
         JSON_OUTPUT3=$(yq -o=json '.batches | to_entries | map(.value | join(",")) | "[" + join(",") + "]"'  .github/input.yaml)
         echo "JSON_OUTPUT is $JSON_OUTPUT"
         echo "JSON_OUTPUT1 is $JSON_OUTPUT1"
         echo "JSON_OUTPUT2 is $JSON_OUTPUT2"
         echo "JSON_OUTPUT3 is $JSON_OUTPUT3"
         echo "json output is $output_test"
         echo "json_single_line is $json_single_line"
        #  echo "output_test=$output_test" >> GITHUB_OUTPUT
        #  echo "json_single_line=$json_single_line" >> GITHUB_OUTPUT

  use-output:
    needs: yq_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use JSON output
        run: |
            echo "JSON output: ${{ needs.yq_test.outputs.output_test }}"


