# .github/workflows/deploy-service.yml
name: Test YQ Service

on:
  push:
  workflow_dispatch: 

jobs:
  yq_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check YQ
        run: |
         ls -R
         JSON_OUTPUT=$(yq '.batches | to_entries | map([.value[]] | join(","))' .github/input.yaml)
         JSON_OUTPUT1=$(yq '.batches | .[] | join(", ")' .github/input.yaml)
         JSON_OUTPUT2=$(yq '.batches | to_entries | map("\"" + (.value | join(", ")) + "\"") | join(", ")' .github/input.yaml | paste -sd "," -)

         output=$(yq -o=json '.batches | to_entries | map(.value | join(","))' .github/input.yaml)
         echo "$JSON_OUTPUT"
         echo "$JSON_OUTPUT1"
         echo "$JSON_OUTPUT2"
         echo "$output"


