# .github/workflows/deploy-service.yml
name: Test YQ Service

on:
  push:
  workflow_dispatch: 

jobs:
  yq_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check YQ
        run: |
         ls -R
         JSON_OUTPUT=$(yq -o=json '.batches | to_entries | map([.value[]] | join(","))' .github/input.yaml)
         echo "$JSON_OUTPUT"


